// Generated by scripts/gen-content-index.mjs. Do not edit by hand.
// One lazy import per authored unit, so a learner only downloads the subjects they chose.
import type { UnitContent } from "./types";

export type UnitKey = `${string}-${number}`;
export type UnitLoader = () => Promise<{ default: UnitContent }>;

export const contentIndex: Record<string, UnitLoader> = {
  "languages-1": () => import("./languages/unit-1"),
  "languages-2": () => import("./languages/unit-2"),
  "languages-3": () => import("./languages/unit-3"),
  "languages-4": () => import("./languages/unit-4"),
  "languages-5": () => import("./languages/unit-5"),
  "languages-6": () => import("./languages/unit-6"),
  "math-1": () => import("./math/unit-1"),
  "math-2": () => import("./math/unit-2"),
  "math-3": () => import("./math/unit-3"),
  "math-4": () => import("./math/unit-4"),
  "math-5": () => import("./math/unit-5"),
  "math-6": () => import("./math/unit-6"),
  "science-1": () => import("./science/unit-1"),
  "science-2": () => import("./science/unit-2"),
  "science-3": () => import("./science/unit-3"),
  "science-4": () => import("./science/unit-4"),
  "science-5": () => import("./science/unit-5"),
};

export const authoredUnits = Object.keys(contentIndex);
